### ISSUE TITLE
Program get stuck when using find_user()

### ISSUE THREAD

**Issue by vishaljangid1729** [Kalebu/alright#45] opened 2022-03-03 05:42 UTC

**Comment by molder26** [comment] 2022-04-07 02:30
I have problem in this function when the whatsapp number is invalid or doesn't exist

**Comment by euriconicacio** [comment] 2022-06-09 06:17
@vishaljangid1729 and @molder26: could you please give us more details so we can try and fix that? Thanks!

**Comment by Kalebu** [comment] 2022-06-09 06:55
Hi @euriconicacio 

I know this issue as I have also previously experienced it, The issue arises when you're trying to find an unsaved contact using ``` messenger.find_user()``` but then the program gets stuck in the way when the number is not on WhatsApp as it will keep waiting for elements to show up which just takes forever 

One way to fix this  will be to put time out for the ```find_user()``` whereby after a certain delay a number will be considered invalid and then we can close the function

**Comment by euriconicacio** [comment] 2022-06-09 06:57
Nice, @Kalebu! I'll work on that asap! Thanks for the guidance!

**Comment by euriconicacio** [comment] 2022-06-18 00:14
I was looking into this and an existing alternative is using `messenger.search_chat_by_name("+1 234 567-8900")`. It's sort of "brute-force" and searches only through non-archived chats, but it is working. Just ran a test with this and it worked nicely (still going to push some additional changes that will make it work, but it's going to be up shortly).

```
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
[WDM] - Driver [/Users/euriconicacio/.wdm/drivers/chromedriver/mac64/102.0.5005.61/chromedriver] found in cache
2022-06-17 20:26:26,287 - root -- [INFO] >> Could not locate chat "+1 234 567-8900"
```

Likewise and even in a deeper/more appropriate way, `messenger.find_by_username("+1 234 567-8900")` works normally for me with the intended purpose - I mean, unless there's a really specific case that justifies the usage of find_user, I think we can go with find_by_username for names, group names and phone numbers (disclaimer: it fetches correctly the chat when the number exists):

```
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
[WDM] - Driver [/Users/euriconicacio/.wdm/drivers/chromedriver/mac64/102.0.5005.61/chromedriver] found in cache
2022-06-17 21:07:46,692 - root -- [INFO] >> It was not possible to fetch chat "+1 234 567-8900"
```

And here the chat being successfully fetched through its number:

```
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
[WDM] - Driver [/Users/euriconicacio/.wdm/drivers/chromedriver/mac64/102.0.5005.61/chromedriver] found in cache
2022-06-17 21:12:38,057 - root -- [INFO] >> Successfully fetched chat "+55 41 9273-2739"
```


Closing this since the issue is solved. @vishaljangid1729 and @molder26, hope this final advice is helpful (using `find_by_username`). @Kalebu, we probably should make this more generic and less repetitive, what do you think?

**Closed by euriconicacio** 2022-06-18 00:14 UTC

**Comment by jchandr** [comment] 2023-05-03 08:15
how is this issue closed?
