### ISSUE TITLE
Unable to send whatsapp messages to unknown/unsaved numbers

### ISSUE THREAD

**Issue by syedizhar1979** [Kalebu/alright#91] opened 2022-11-22 07:10 UTC
Dear Members, please help me regarding whatsapp messages send by ALRIGHT ... it starts happens when whatsapp updates themselves 

i have a unsaved number and i am trying to send messages but error is returning
**2022-11-22 11:54:15,478 - root -- [INFO] >> 4**  

my code is under
>>> from alright import WhatsApp
>>> messenger = WhatsApp()
>>> messenger.find_user('+923461234567')

i also tried without + sign but unable to send

**Comment by syedizhar1979** [comment] 2022-11-22 07:27
![invalid whatsappno](https://user-images.githubusercontent.com/53652333/203251504-2a73bf73-37ef-4e9e-955f-f692f6a730a6.JPG)

**Comment by Kalebu** [comment] 2022-11-22 08:24
This error message shows that the number you're trying to find does not have a valid WhatsApp Account. 

> This Method will only work for numbers with valid account otherwise it will fail 

@syedizhar1979

**Comment by syedizhar1979** [comment] 2022-11-22 10:00
Dear Mr. Kalebu, i am using the valid number on it but it only allows me to send message for those who are already added in my contact list/whatsapp list
so i am trying to clear you once again that on unknown/unsaved your code is not working

**Comment by syedizhar1979** [comment] 2022-11-22 10:33
you can check this number +923468203866, this is original number of my customer, which is not added in my contact list or whatsapp list
so this is new number/unknown number or unsaved number, where whatsapp is not allowing to send direct message
and giving error


![image-whatsapp](https://user-images.githubusercontent.com/53652333/203291473-54658c5d-d674-4dd9-991a-bbfedb8641df.jpeg)

**Comment by syedizhar1979** [comment] 2022-11-22 10:33
the above whatsapp picture showing that number is exist on whatsapp

**Comment by syedizhar1979** [comment] 2022-11-22 10:35
i would like to advise you all that please check this alright wrapper code on new/unsaved/unknown whatsapp number, now whatsapp increases the security last week through its new update, please check

**Comment by Kalebu** [comment] 2022-11-22 11:47
Thank you for clarifying and letting us know 

We look into and see if there are ways around this 

@syedizhar1979  @euriconicacio

**Comment by syedizhar1979** [comment] 2022-11-23 05:12
@Kalebu i am waiting for this

**Comment by matanmoshe** [comment] 2022-11-23 14:37
I encounter the same issue..
Worked 2 weeks ago and now fails to find unsaved contacts

**Comment by Kalebu** [comment] 2022-12-02 22:23
Hello @syedizhar1979 @matanmoshe 

Are you still experiencing the issue, just tried seconds ago for unsaved number it worked 

Please let me know ?

**Comment by matanmoshe** [comment] 2022-12-05 09:31
@Kalebu looks like the issue is resolved

**Comment by syedizhar1979** [comment] 2022-12-06 09:13
@Kalebu yes thanks, issue resolved but what was the issue? you update it or Whatsapp did it by themselves ???

**Comment by Kalebu** [comment] 2022-12-07 06:21
Good to hear this  @syedizhar1979  @matanmoshe 

I haven't changed anything, It was an update done WhatsApp  themselves 

I will now close this issue

**Closed by Kalebu** 2022-12-07 06:21 UTC
